FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt ./
RUN python -m pip install --upgrade pip && \
    pip install -r requirements.txt

COPY frontend ./frontend
COPY run_frontend.py ./

EXPOSE 8501

# 프록스목스 배포를 위한 환경 변수 설정
ENV BACKEND_URL=http://211.227.149.168:5555 \
    STREAMLIT_SERVER_ADDRESS=0.0.0.0 \
    STREAMLIT_SERVER_PORT=8501

CMD ["python", "run_frontend.py"]

