name: Commit Message Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check commit messages
      run: |
        # Check if commit messages follow Conventional Commits format
        git log --format="%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | while read msg; do
          if ! echo "$msg" | grep -qE "^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+"; then
            echo "❌ Invalid commit message format: $msg"
            echo "Please follow Conventional Commits format: type(scope): description"
            exit 1
          else
            echo "✅ Valid commit message: $msg"
          fi
        done