name: Commit Message Validation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Validate commit messages
      run: |
        echo "🔍 Checking commit messages for Conventional Commits format..."
        
        # Get commit messages in the PR
        COMMITS=$(git log --format="%H %s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
        
        # Pattern for Conventional Commits
        PATTERN="^(feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert)(\(.+\))?: .+"
        
        INVALID_COUNT=0
        
        while IFS= read -r line; do
          if [ -n "$line" ]; then
            COMMIT_HASH=$(echo "$line" | cut -d' ' -f1)
            COMMIT_MSG=$(echo "$line" | cut -d' ' -f2-)
            
            if echo "$COMMIT_MSG" | grep -qE "$PATTERN"; then
              echo "✅ Valid: $COMMIT_MSG"
            else
              echo "❌ Invalid: $COMMIT_MSG"
              echo "   Commit: $COMMIT_HASH"
              INVALID_COUNT=$((INVALID_COUNT + 1))
            fi
          fi
        done <<< "$COMMITS"
        
        if [ $INVALID_COUNT -gt 0 ]; then
          echo ""
          echo "🚨 Found $INVALID_COUNT invalid commit message(s)!"
          echo ""
          echo "📋 Conventional Commits 형식을 따라주세요:"
          echo "   type(scope): description"
          echo ""
          echo "   Types: feat, fix, docs, style, refactor, test, chore"
          echo "   Examples:"
          echo "   - feat(auth): 소셜 로그인 기능 추가"
          echo "   - fix(api): 사용자 정보 누락 문제 수정"
          echo "   - docs: README.md 업데이트"
          exit 1
        else
          echo ""
          echo "🎉 All commit messages are valid!"
        fi